services:
  frontend:
    container_name: frontend
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: rublin322/picscore-frontend:latest
    networks:
      - picscore-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: rublin322/picscore-backend:latest
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    networks:
      - picscore-network
  
  proxy:
    container_name: proxy
    image: nginx:1.26-alpine
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      - picscore-network

  mysql:
    container_name: mysql
    image: mysql:8.4
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - picscore-network

  redis:
    container_name: redis
    image: redis:7.4-alpine
    env_file:
      - .env
    networks:
      - picscore-network

volumes:
  mysql-data:
    name: mysql-data

networks:
  picscore-network:
    name: picscore-network
    driver: bridge