services:
  frontend:
    ports:
      - "5173:80"

  backend:
    ports:
      - "8080:8080"

  proxy:
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
  
  mysql:
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"